//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sfShareLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CDStudioEntities : DbContext
    {
        public CDStudioEntities()
            : base("name=CDStudioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccumulateUsageLog> AccumulateUsageLog { get; set; }
        public virtual DbSet<APIServiceRefreshToken> APIServiceRefreshToken { get; set; }
        public virtual DbSet<APIServiceRole> APIServiceRole { get; set; }
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CompanyInSubscriptionPlan> CompanyInSubscriptionPlan { get; set; }
        public virtual DbSet<Dashboard> Dashboard { get; set; }
        public virtual DbSet<DashboardWidgets> DashboardWidgets { get; set; }
        public virtual DbSet<DeviceCertificate> DeviceCertificate { get; set; }
        public virtual DbSet<DeviceCommandCatalog> DeviceCommandCatalog { get; set; }
        public virtual DbSet<DeviceType> DeviceType { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmployeeInRole> EmployeeInRole { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<EquipmentClass> EquipmentClass { get; set; }
        public virtual DbSet<EquipmentClassMessageCatalog> EquipmentClassMessageCatalog { get; set; }
        public virtual DbSet<EquipmentEnrollment> EquipmentEnrollment { get; set; }
        public virtual DbSet<ErrorMessage> ErrorMessage { get; set; }
        public virtual DbSet<EventInAction> EventInAction { get; set; }
        public virtual DbSet<EventRuleCatalog> EventRuleCatalog { get; set; }
        public virtual DbSet<EventRuleItem> EventRuleItem { get; set; }
        public virtual DbSet<ExternalDashboard> ExternalDashboard { get; set; }
        public virtual DbSet<Factory> Factory { get; set; }
        public virtual DbSet<IoTDevice> IoTDevice { get; set; }
        public virtual DbSet<IoTDeviceCommand> IoTDeviceCommand { get; set; }
        public virtual DbSet<IoTDeviceCustomizedConfiguration> IoTDeviceCustomizedConfiguration { get; set; }
        public virtual DbSet<IoTDeviceSystemConfiguration> IoTDeviceSystemConfiguration { get; set; }
        public virtual DbSet<IoTHub> IoTHub { get; set; }
        public virtual DbSet<MessageCatalog> MessageCatalog { get; set; }
        public virtual DbSet<MessageElement> MessageElement { get; set; }
        public virtual DbSet<MessageMandatoryElementDef> MessageMandatoryElementDef { get; set; }
        public virtual DbSet<MetaDataDefination> MetaDataDefination { get; set; }
        public virtual DbSet<MetaDataValue> MetaDataValue { get; set; }
        public virtual DbSet<OperationTask> OperationTask { get; set; }
        public virtual DbSet<PermissionCatalog> PermissionCatalog { get; set; }
        public virtual DbSet<RefCultureInfo> RefCultureInfo { get; set; }
        public virtual DbSet<SubscriptionPlan> SubscriptionPlan { get; set; }
        public virtual DbSet<SuperAdmin> SuperAdmin { get; set; }
        public virtual DbSet<SystemConfiguration> SystemConfiguration { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<UserRolePermission> UserRolePermission { get; set; }
        public virtual DbSet<WidgetCatalog> WidgetCatalog { get; set; }
        public virtual DbSet<WidgetClass> WidgetClass { get; set; }
    }
}
