//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sfShareLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dashboard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dashboard()
        {
            this.DashboardWidgets = new HashSet<DashboardWidgets>();
        }
    
        public int Id { get; set; }
        public int CompanyID { get; set; }
        public string DashboardType { get; set; }
        public Nullable<int> FactoryID { get; set; }
        public Nullable<int> EquipmentClassID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual EquipmentClass EquipmentClass { get; set; }
        public virtual Factory Factory { get; set; }
        public virtual Equipment Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashboardWidgets> DashboardWidgets { get; set; }
    }
}
