//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sfShareLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardWidgets
    {
        public int Id { get; set; }
        public int DashboardID { get; set; }
        public int WidgetCatalogID { get; set; }
        public int RowNo { get; set; }
        public Nullable<int> ColumnSeq { get; set; }
        public int WidthSpace { get; set; }
        public int HeightPixel { get; set; }
    
        public virtual Dashboard Dashboard { get; set; }
        public virtual WidgetCatalog WidgetCatalog { get; set; }
    }
}
