//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sfShareLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventRuleCatalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventRuleCatalog()
        {
            this.EventInAction = new HashSet<EventInAction>();
            this.EventRuleItem = new HashSet<EventRuleItem>();
        }
    
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int MessageCatalogId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int AggregateInSec { get; set; }
        public bool ActiveFlag { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventInAction> EventInAction { get; set; }
        public virtual MessageCatalog MessageCatalog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventRuleItem> EventRuleItem { get; set; }
    }
}
