//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sfShareLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class IoTHub
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IoTHub()
        {
            this.IoTDevice = new HashSet<IoTDevice>();
        }
    
        public int Id { get; set; }
        public string IoTHubName { get; set; }
        public string Description { get; set; }
        public int CompanyID { get; set; }
        public string IoTHubEndPoint { get; set; }
        public string IoTHubConnectionString { get; set; }
        public string EventConsumerGroup { get; set; }
        public string EventHubStorageConnectionString { get; set; }
        public string UploadContainer { get; set; }
        public bool EnableMultipleReceiver { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IoTDevice> IoTDevice { get; set; }
    }
}
