//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sfShareLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageMandatoryElementDef
    {
        public int Id { get; set; }
        public string ElementName { get; set; }
        public string ElementDataType { get; set; }
        public bool MandatoryFlag { get; set; }
        public string Description { get; set; }
    }
}
