//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sfShareLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaDataValue
    {
        public int Id { get; set; }
        public int MetaDataDefinationId { get; set; }
        public string ObjectValue { get; set; }
        public int ReferenceId { get; set; }
    
        public virtual MetaDataDefination MetaDataDefination { get; set; }
    }
}
