//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sfShareLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SFDatabaseEntities : DbContext
    {
        public SFDatabaseEntities()
            : base("name=SFDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlarmNotification> AlarmNotification { get; set; }
        public virtual DbSet<AlarmRuleCatalog> AlarmRuleCatalog { get; set; }
        public virtual DbSet<AlarmRuleItem> AlarmRuleItem { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Dashboard> Dashboard { get; set; }
        public virtual DbSet<DashboardWidgets> DashboardWidgets { get; set; }
        public virtual DbSet<DeviceCertificate> DeviceCertificate { get; set; }
        public virtual DbSet<DeviceType> DeviceType { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmployeeInRole> EmployeeInRole { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<EquipmentClass> EquipmentClass { get; set; }
        public virtual DbSet<ExternalApplication> ExternalApplication { get; set; }
        public virtual DbSet<ExternalDashboard> ExternalDashboard { get; set; }
        public virtual DbSet<Factory> Factory { get; set; }
        public virtual DbSet<IoTDevice> IoTDevice { get; set; }
        public virtual DbSet<IoTDeviceConfiguration> IoTDeviceConfiguration { get; set; }
        public virtual DbSet<IoTDeviceCustomizedConfiguration> IoTDeviceCustomizedConfiguration { get; set; }
        public virtual DbSet<IoTDeviceMessageCatalog> IoTDeviceMessageCatalog { get; set; }
        public virtual DbSet<IoTHub> IoTHub { get; set; }
        public virtual DbSet<MessageCatalog> MessageCatalog { get; set; }
        public virtual DbSet<MessageElement> MessageElement { get; set; }
        public virtual DbSet<MessageMandatoryElementDef> MessageMandatoryElementDef { get; set; }
        public virtual DbSet<OperationTask> OperationTask { get; set; }
        public virtual DbSet<PermissionCatalog> PermissionCatalog { get; set; }
        public virtual DbSet<RefCultureInfo> RefCultureInfo { get; set; }
        public virtual DbSet<SuperAdmin> SuperAdmin { get; set; }
        public virtual DbSet<UsageLog> UsageLog { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<UserRolePermission> UserRolePermission { get; set; }
        public virtual DbSet<WidgetCatalog> WidgetCatalog { get; set; }
        public virtual DbSet<WidgetClass> WidgetClass { get; set; }
        public virtual DbSet<UsageLogSumByDay> UsageLogSumByDay { get; set; }
    }
}
