//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sfShareLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubscriptionPlan()
        {
            this.CompanyInSubscriptionPlan = new HashSet<CompanyInSubscriptionPlan>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<double> DefaultRatePer1KMessageIngestion { get; set; }
        public Nullable<double> DefaultRatePer1KMessageHotStore { get; set; }
        public Nullable<double> DefaultRatePer1KMessageColdStore { get; set; }
        public int DefaultPlanDays { get; set; }
        public int DefaultMaxMessageQuotaPerDay { get; set; }
        public Nullable<bool> DefaultStoreHotMessage { get; set; }
        public Nullable<bool> DefaultStoreColdMessage { get; set; }
        public string DefaultCosmosDBConnectionString { get; set; }
        public Nullable<int> DefaultCollectionTTL { get; set; }
        public Nullable<int> DefaultCollectionReservedUnits { get; set; }
        public string DefaultIoTHubConnectionString { get; set; }
        public string DefaultStorageConnectionString { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyInSubscriptionPlan> CompanyInSubscriptionPlan { get; set; }
    }
}
