//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sfShareLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class WidgetCatalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WidgetCatalog()
        {
            this.DashboardWidgets = new HashSet<DashboardWidgets>();
        }
    
        public int Id { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> MessageCatalogID { get; set; }
        public string Name { get; set; }
        public string Level { get; set; }
        public int WidgetClassKey { get; set; }
        public string Title { get; set; }
        public string TitleBgColor { get; set; }
        public string Content { get; set; }
        public string ContentBgColor { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DashboardWidgets> DashboardWidgets { get; set; }
        public virtual MessageCatalog MessageCatalog { get; set; }
        public virtual WidgetClass WidgetClass { get; set; }
    }
}
