//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sfShareLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class WidgetClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WidgetClass()
        {
            this.WidgetCatalog = new HashSet<WidgetCatalog>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Key { get; set; }
        public string Level { get; set; }
        public string PhotoURL { get; set; }
        public bool AllowMultipleAppearOnBoard { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WidgetCatalog> WidgetCatalog { get; set; }
    }
}
