//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSShareLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccumulateUsageLog
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> FactoryQty { get; set; }
        public Nullable<int> EquipmentQty { get; set; }
        public long MessageQty { get; set; }
        public long DocSizeInMB { get; set; }
        public int BlobSizeInMB { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
