//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSShareLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceCertificate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeviceCertificate()
        {
            this.IoTDevice = new HashSet<IoTDevice>();
        }
    
        public int Id { get; set; }
        public int CompanyID { get; set; }
        public string Name { get; set; }
        public string CertFile { get; set; }
        public string KeyFile { get; set; }
        public string Thumbprint { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> ExpiredAt { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IoTDevice> IoTDevice { get; set; }
    }
}
