//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSShareLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.Dashboard = new HashSet<Dashboard>();
        }
    
        public int Id { get; set; }
        public string EquipmentId { get; set; }
        public string Name { get; set; }
        public int EquipmentClassId { get; set; }
        public int CompanyID { get; set; }
        public int FactoryId { get; set; }
        public int IoTDeviceID { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public int MaxIdleInSec { get; set; }
        public string PhotoURL { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dashboard> Dashboard { get; set; }
        public virtual Factory Factory { get; set; }
        public virtual EquipmentClass EquipmentClass { get; set; }
        public virtual IoTDevice IoTDevice { get; set; }
    }
}
