//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSShareLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentEnrollment
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int FactoryId { get; set; }
        public int EquipmentClassId { get; set; }
        public string EquipmentId { get; set; }
        public string ActivationKey { get; set; }
        public System.DateTime EnrollDate { get; set; }
        public int SuperAdminId { get; set; }
        public bool IsActivated { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public System.DateTime ActivationExpiredAt { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual EquipmentClass EquipmentClass { get; set; }
        public virtual Factory Factory { get; set; }
        public virtual SuperAdmin SuperAdmin { get; set; }
    }
}
