//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSShareLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalDashboard
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int Ordering { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
