//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSShareLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class IoTDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IoTDevice()
        {
            this.Equipment = new HashSet<Equipment>();
        }
    
        public int Id { get; set; }
        public string IoTHubDeviceID { get; set; }
        public string IoTHubDevicePW { get; set; }
        public string IoTHubDeviceKey { get; set; }
        public int IoTHubID { get; set; }
        public string IoTHubProtocol { get; set; }
        public int CompanyID { get; set; }
        public int FactoryID { get; set; }
        public string AuthenticationType { get; set; }
        public Nullable<int> DeviceCertificateID { get; set; }
        public int DeviceTypeId { get; set; }
        public string DeviceVendor { get; set; }
        public string DeviceModel { get; set; }
        public string MessageConvertScript { get; set; }
        public bool EnableMessageConvert { get; set; }
        public string OriginMessage { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual DeviceCertificate DeviceCertificate { get; set; }
        public virtual DeviceType DeviceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment> Equipment { get; set; }
        public virtual Factory Factory { get; set; }
        public virtual IoTHub IoTHub { get; set; }
    }
}
