//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSShareLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MessageElement()
        {
            this.EventRuleItem = new HashSet<EventRuleItem>();
            this.EventRuleItem1 = new HashSet<EventRuleItem>();
        }
    
        public int Id { get; set; }
        public int MessageCatalogID { get; set; }
        public string ElementName { get; set; }
        public string ElementDataType { get; set; }
        public Nullable<int> ChildMessageCatalogID { get; set; }
        public bool MandatoryFlag { get; set; }
        public bool CDSMandatoryFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventRuleItem> EventRuleItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventRuleItem> EventRuleItem1 { get; set; }
        public virtual MessageCatalog MessageCatalog { get; set; }
    }
}
