//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDSShareLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationTask
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string TaskStatus { get; set; }
        public Nullable<System.DateTime> CompletedAt { get; set; }
        public int RetryCounter { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Entity { get; set; }
        public string EntityId { get; set; }
        public string TaskContent { get; set; }
        public string TaskLog { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public bool DeletedFlag { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
