SET IDENTITY_INSERT [CDS20].[SuperAdmin] ON
INSERT INTO [CDS20].[SuperAdmin] ([Id], [FirstName], [LastName], [Email], [Password], [CreatedAt], [UpdatedAt], [DeletedFlag]) VALUES (1, N'Super', N'Admin', N'super@cdstudio.com', N'AFns/VMam+LzA9lb9bvrSlFyLSJf1fP/C/sU7hoHDCTMaaQLKEfX9yb7V3qyXLWtEg==', N'2017-09-03 19:18:08', NULL, 0)
SET IDENTITY_INSERT [CDS20].[SuperAdmin] OFF

SET IDENTITY_INSERT [CDS20].[DeviceType] ON
INSERT INTO [CDS20].[DeviceType] ([Id], [Name], [Description]) VALUES (1, N'Device', NULL)
INSERT INTO [CDS20].[DeviceType] ([Id], [Name], [Description]) VALUES (2, N'Gateway', NULL)
INSERT INTO [CDS20].[DeviceType] ([Id], [Name], [Description]) VALUES (3, N'Azure IoT Edge', NULL)
SET IDENTITY_INSERT [CDS20].[DeviceType] OFF

INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (10101, N'Wrong password.', N'Authentication', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (10102, N'Application not found.', N'Application', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (10103, N'MessageTemplate should be JSON format.', N'Application', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (10301, N'Company not found.', N'Company', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (10302, N'Subscription Plan of the Company not found.', N'Company', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (10303, N'Valid Subscription Plan of hte Company not found.', N'Company', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (10401, N'DeviceCertificate not found', N'DeviceCertificate', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (10402, N'Dashboard not found', N'Dashboard', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (10501, N'Equipment not found', N'Equipment', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (10502, N'ExternalDashboard not found', N'ExternalDashboard', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (10503, N'EquipmentId should be unique.', N'Equipment', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (10601, N'Factory not found', N'Factory', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (10701, N'Resource not found.', N'General', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (10702, N'The name is duplicated.', N'General', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (10901, N'IoTHub not found.', N'IoT Hub', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (10902, N'IoTDevice not found.', N'IoTDevice', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (10903, N'DeviceTwinDesired should be JSON format.', N'IoTDevice', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (10904, N'IoTHubDeviceId should be unique.', N'IoTDevice', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (11301, N'MetaDataDefiniation not found', N'MetaDataDefiniation', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (11302, N'EntityType + ObjectName should be unique.', N'MetaDataDefiniation', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (11501, N'TaskContent should be JSON format.', N'OperationTask', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (11901, N'SystemConfiguration not found', N'SystemConfiguration', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (11902, N'Key should be unique.', N'SystemConfiguration', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (11903, N'Subscription Plan not found.', N'Subscription', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (12101, N'Usage Log not found.', N'UsageLogs', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (12102, N'Last Usage Log not found', N'UsageLogs', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (12103, N'User Role not found', N'UserRole', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (12104, N'The name is duplicated.', N'UserRole', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (12301, N'WidgetClass not found.', N'WidgetClass', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (12302, N'WidgeCatalog not found.', N'WidgeCatalog', N'API')
INSERT INTO [CDS20].[ErrorMessage] ([Id], [Message], [Category], [App]) VALUES (12303, N'Content should be JSON format', N'WidgeCatalog', N'API')



SET IDENTITY_INSERT [CDS20].[MessageMandatoryElementDef] ON
INSERT INTO [CDS20].[MessageMandatoryElementDef] ([Id], [ElementName], [ElementDataType], [MandatoryFlag], [Description]) VALUES (1, N'companyId', N'numeric', 1, NULL)
INSERT INTO [CDS20].[MessageMandatoryElementDef] ([Id], [ElementName], [ElementDataType], [MandatoryFlag], [Description]) VALUES (2, N'msgTimestamp', N'datetime', 1, N'2016-12-01 08:00:00 (local time)')
INSERT INTO [CDS20].[MessageMandatoryElementDef] ([Id], [ElementName], [ElementDataType], [MandatoryFlag], [Description]) VALUES (3, N'equipmentId', N'string', 1, NULL)
INSERT INTO [CDS20].[MessageMandatoryElementDef] ([Id], [ElementName], [ElementDataType], [MandatoryFlag], [Description]) VALUES (4, N'equipmentRunStatus', N'numeric', 1, N'-1: stop | 0: idle | 1: run')
SET IDENTITY_INSERT [CDS20].[MessageMandatoryElementDef] OFF


SET IDENTITY_INSERT [CDS20].[PermissionCatalog] ON
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (1, N'Factory View', NULL, 10)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (2, N'Factory Edit', NULL, 11)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (3, N'Equipment View', NULL, 20)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (4, N'Equipment Edit', NULL, 21)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (5, N'IoT Device View', NULL, 30)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (6, N'IoT Device Edit', NULL, 31)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (7, N'IoT Device Configuration Management View', NULL, 32)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (8, N'IoT Device Configuration Management Edit', NULL, 33)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (9, N'IoT Device Message Attach View', NULL, 34)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (10, N'IoT Device Message Attach Edit', NULL, 35)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (11, N'Message View', NULL, 40)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (12, N'Message Edit', NULL, 41)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (13, N'Message Element View', NULL, 42)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (14, N'Message Element Edit', NULL, 43)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (15, N'Monitor Running Task', NULL, 50)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (16, N'Monitor IoT Hubs', NULL, 51)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (17, N'Monitor Usage Log', NULL, 52)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (18, N'Setup Event Rule Catalog', NULL, 100)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (19, N'Setup Event Notify', NULL, 101)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (20, N'Setup Device Certificate', NULL, 102)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (21, N'Setup Employee', NULL, 104)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (22, N'Setup Role', NULL, 105)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (23, N'Setup External Application', NULL, 107)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (24, N'Setup Widget Catalog', NULL, 108)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (25, N'Setup Device Configuration', N'Setup Device Configuration', 109)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (26, N'Setup Equipment Class', N'Setup Equipment Class', 110)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (27, N'Dashboard Company View', N'View permission of Company of Dashboard', 60)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (28, N'Dashboard Factory View', N'View permission of Factory of Dashboard', 61)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (29, N'Dashboard Equipment View', N'View permission of Equipment of Dashboard', 62)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (31, N'Dashboard Company Edit', N'Edit permission for Company of Dashboard', 63)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (32, N'Dashboard Factory Edit', N'Edit permission for Factory of Dashboard', 64)
INSERT INTO [CDS20].[PermissionCatalog] ([Id], [Name], [Description], Code) VALUES (33, N'Dashboard Equipment Edit', N'Edit permission of Equipment Dashboard', 65)
SET IDENTITY_INSERT [CDS20].[PermissionCatalog] OFF

INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'aa', N'Afar')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ab', N'Abkhazian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'af-ZA', N'Afrikaans')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'am', N'Amharic')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar', N'Arabic')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-AE', N'Arabic (Uae)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-BH', N'Arabic (Bahrain)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-DZ', N'Arabic (Algeria)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-EG', N'Arabic (Egypt)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-IQ', N'Arabic (Iraq)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-JO', N'Arabic (Jordan)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-KW', N'Arabic (Kuwait)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-LB', N'Arabic (Lebanon)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-LY', N'Arabic (Libya)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-MA', N'Arabic (Morocco)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-OM', N'Arabic (Oman)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-QA', N'Arabic (Qatar)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-SA', N'Arabic (Saudi Arabia)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-SD', N'Arabic (Sudan)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-SY', N'Arabic (Syria)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-TN', N'Arabic (Tunisia)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ar-YE', N'Arabic (Yemen)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'as', N'Assamese')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ay', N'Aymara')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'az', N'Azeri')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ba', N'Bashkir')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'be-BY', N'Belarusian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'bg-BG', N'Bulgarian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'bh', N'Bihari')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'bi', N'Bislama')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'bn', N'Bengali')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'bo', N'Tibetan')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'br', N'Breton')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ca-ES', N'Catalan')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'co', N'Corsican')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'cs-CZ', N'Czech')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'cy', N'Welsh')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'da-DK', N'Danish')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'de-AT', N'German (Austrian)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'de-BE', N'German (Belgium)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'de-CH', N'German (Swiss)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'de-DE', N'German')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'de-LI', N'German (Liechtenstein)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'de-LU', N'German (Luxembourg)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'dz', N'Bhutani')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'el-GR', N'Greek')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-AU', N'English (Australia)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-BW', N'English (Botswana)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-BZ', N'English (Belize)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-CA', N'English (Canada)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-CB', N'English (Caribbean)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-DK', N'English (Denmark)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-GB', N'English')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-IE', N'English (Eire)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-JM', N'English (Jamaica)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-NZ', N'English (New Zealand)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-PH', N'English (Philippines)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-TT', N'English (Trinidad)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-US', N'English (U.S.)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-ZA', N'English (South Africa)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'en-ZW', N'English (Zimbabwe)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'eo', N'Esperanto')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-AR', N'Spanish (Argentina)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-BO', N'Spanish (Bolivia)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-CL', N'Spanish (Chile)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-CO', N'Spanish (Colombia)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-CR', N'Spanish (Costa Rica)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-DO', N'Spanish (Dominican republic)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-EC', N'Spanish (Ecuador)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-ES', N'Spanish')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-GT', N'Spanish (Guatemala)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-HN', N'Spanish (Honduras)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-MX', N'Spanish (Mexican)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-NI', N'Spanish (Nicaragua)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-PA', N'Spanish (Panama)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-PE', N'Spanish (Peru)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-PR', N'Spanish (Puerto Rico)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-PY', N'Spanish (Paraguay)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-SV', N'Spanish (El Salvador)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-US', N'Spanish (U.S.)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-UY', N'Spanish (Uruguay)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'es-VE', N'Spanish (Venezuela)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'et-EE', N'Estonian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'eu-ES', N'Basque')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'fa-IR', N'Farsi')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'fi-FI', N'Finnish')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'fj', N'Fiji')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'fo-FO', N'Faeroese')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'fr-BE', N'French (Belgian)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'fr-CA', N'French (Canadian)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'fr-CH', N'French (Swiss)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'fr-FR', N'French')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'fr-LU', N'French (Luxembourg)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'fr-MC', N'French (Monaco)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'fy', N'Frisian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ga-IE', N'Irish')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'gd', N'Scots Gaelic')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'gl-ES', N'Galician')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'gn', N'Guarani')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'gu', N'Gujarati')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ha', N'Hausa')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'he-IL', N'Hebrew')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'hi-IN', N'Hindi')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'hr-HR', N'Croatian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'hu-HU', N'Hungarian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'hy', N'Armenian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ia', N'Interlingua')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'id-ID', N'Indonesian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ie', N'Interlingue')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ik', N'Inupiak')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'is-IS', N'Icelandic')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'it-CH', N'Italian (Swiss)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'it-IT', N'Italian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'iu', N'Inuktitut')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ja-JP', N'Japanese')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'jw', N'Javanese')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ka-GE', N'Georgian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'kk', N'Kazakh')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'kl-GL', N'Greenlandic')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'km', N'Cambodian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'kn', N'Kannada')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ko-KR', N'Korean')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ks', N'Kashmiri')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ks-IN', N'Kashmiri (India)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ku-TR', N'Kurdish')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'kw-GB', N'Kernewek')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ky', N'Kirghiz')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'la', N'Latin')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ln', N'Lingala')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'lo', N'Laothian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'lt-LT', N'Lithuanian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'lv-LV', N'Latvian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'mg', N'Malagasy')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'mi', N'Maori')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'mk-MK', N'Macedonian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ml', N'Malayalam')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'mn', N'Mongolian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'mo', N'Moldavian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'mr-IN', N'Marathi')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ms-BN', N'Malay (Brunei Darussalam)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ms-MY', N'Malay')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'mt-MT', N'Maltese')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'my', N'Burmese')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'na', N'Nauru')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'nb-NO', N'Norwegian (Bokmal)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ne-IN', N'Nepali (India)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ne-NP', N'Nepali')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'nl-BE', N'Dutch (Belgian)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'nl-NL', N'Dutch')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'nn-NO', N'Norwegian (Nynorsk)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'oc', N'Occitan')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'om', N'(Afan) Oromo')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'or', N'Oriya')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'pa', N'Punjabi')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'pl-PL', N'Polish')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ps', N'Pashto, Pushto')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'pt-BR', N'Portuguese (Brazilian)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'pt-PT', N'Portuguese')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'qu', N'Quechua')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'rm', N'Rhaeto-Romance')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'rn', N'Kirundi')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ro-RO', N'Romanian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ru-RU', N'Russian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ru-UA', N'Russian (Ukraine)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'rw', N'Kinyarwanda')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sa', N'Sanskrit')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sd', N'Sindhi')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'se-NO', N'Northern Sami')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sg', N'Sangho')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sh', N'Serbo-Croatian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'si', N'Sinhalese')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sk-SK', N'Slovak')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sl-SI', N'Slovenian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sm', N'Samoan')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sn', N'Shona')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'so', N'Somali')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sq-AL', N'Albanian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sr-SR', N'Serbian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sr-SR@lati', N'Serbian (Latin)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ss', N'Siswati')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'st', N'Sesotho')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'su', N'Sundanese')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sv-FI', N'Swedish (Finland)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sv-SE', N'Swedish')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'sw-KE', N'Swahili')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ta', N'Tamil')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'te', N'Telugu')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'tg', N'Tajik')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'th-TH', N'Thai')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ti', N'Tigrinya')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'tk', N'Turkmen')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'tl-PH', N'Tagalog')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'tn', N'Setswana')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'to', N'Tonga')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'tr-TR', N'Turkish')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ts', N'Tsonga')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'tt', N'Tatar')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'tw', N'Twi')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ug', N'Uighur')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'uk-UA', N'Ukrainian')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ur', N'Urdu')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ur-IN', N'Urdu (India)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'ur-PK', N'Urdu (Pakistan)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'uz', N'Uzbek')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'vi-VN', N'Vietnamese')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'vo', N'Volapuk')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'wo', N'Wolof')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'xh', N'Xhosa')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'yi', N'Yiddish')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'yo', N'Yoruba')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'za', N'Zhuang')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'zh-CN', N'Chinese (Simplified)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'zh-HK', N'Chinese (Hongkong)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'zh-MO', N'Chinese (Macau)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'zh-SG', N'Chinese (Singapore)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'zh-TW', N'Chinese (Taiwan)')
INSERT INTO [CDS20].[RefCultureInfo] ([CultureCode], [Name]) VALUES (N'zu', N'Zulu')

SET IDENTITY_INSERT [CDS20].[WidgetClass] ON
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (1, N'Event Card', 100, N'company', N'/assets/images/widget/EventCard.PNG', 1)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (2, N'Event List', 101, N'company', N'/assets/images/widget/EventList.PNG', 0)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (3, N'Equipment Card', 102, N'company', N'/assets/images/widget/EquipmentCard.PNG', 0)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (4, N'Factory Card', 103, N'company', N'/assets/images/widget/FactoryCard.PNG', 0)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (5, N'Factory List', 104, N'company', N'/assets/images/widget/FactoryList.PNG', 0)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (6, N'Google Map Card', 105, N'company', N'/assets/images/widget/GoogleMapCard.PNG', 0)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (7, N'Logo Card', 106, N'company', N'/assets/images/widget/CompanyLogoCard.PNG', 1)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (8, N'HTML Content Card', 107, N'company', N'/assets/images/widget/HTMLContent.PNG', 1)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (9, N'Event Card', 200, N'factory', N'/assets/images/widget/EventCard.PNG', 1)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (10, N'Event List', 201, N'factory', N'/assets/images/widget/EventList.PNG', 0)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (11, N'Company Logo Card', 202, N'factory', N'/assets/images/widget/CompanyLogoCard.PNG', 1)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (12, N'Equipment Card', 203, N'factory', N'/assets/images/widget/EquipmentCard.PNG', 0)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (13, N'Equipment List', 204, N'factory', N'/assets/images/widget/EquipmentList.PNG', 0)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (14, N'Google Map Card', 205, N'factory', N'/assets/images/widget/GoogleMapCard.PNG', 0)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (15, N'Factory Photo Card', 206, N'factory', N'/assets/images/widget/FactoryPhotoCard.PNG', 1)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (16, N'Video Card', 207, N'factory', N'/assets/images/widget/VideoCard.PNG', 1)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (17, N'HTML Content Card', 208, N'factory', N'/assets/images/widget/HTMLContent.PNG', 1)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (18, N'Event Card', 300, N'equipment', N'/assets/images/widget/EventCard.PNG', 1)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (19, N'Bar Chart', 301, N'equipment', N'/assets/images/widget/BarChart.PNG', 1)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (20, N'Basic Card', 302, N'equipment', N'/assets/images/widget/BasicCard.PNG', 0)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (21, N'Google Map Card', 303, N'equipment', N'/assets/images/widget/GoogleMapCard.PNG', 0)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (22, N'Line Chart', 304, N'equipment', N'/assets/images/widget/LineChart.PNG', 1)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (23, N'Percentage Card', 305, N'equipment', N'/assets/images/widget/PercentageCard.PNG', 1)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (24, N'Pie Chart', 306, N'equipment', N'/assets/images/widget/PieChart.png', 1)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (25, N'Text Card', 307, N'equipment', N'/assets/images/widget/TextCard.PNG', 1)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (26, N'Text List Card', 308, N'equipment', N'/assets/images/widget/TextListCard.PNG', 1)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (27, N'Event List', 309, N'equipment', N'/assets/images/widget/EventList.PNG', 0)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (28, N'Google Map Location Trace', 310, N'equipment', N'/assets/images/widget/GoogleMapLocationTrace.PNG', 0)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (29, N'Simple OEE', 311, N'equipment', N'/assets/images/widget/SimpleOEE.PNG', 1)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (30, N'Preferred OEE', 312, N'equipment', N'/assets/images/widget/PreferredOEE.PNG', 1)
INSERT INTO [CDS20].[WidgetClass] ([Id], [Name], [Key], [Level], [PhotoURL], [AllowMultipleAppearOnBoard]) VALUES (31, N'HTML Content Card', 313, N'equipment', N'/assets/images/widget/HTMLContent.PNG', 1)
SET IDENTITY_INSERT [CDS20].[WidgetClass] OFF

SET IDENTITY_INSERT [CDS20].[SubscriptionPlan] ON
INSERT INTO [CDS20].[SubscriptionPlan] ([Id], [Name], [Description], [DefaultRatePer1KMessageIngestion], [DefaultRatePer1KMessageHotStore], [DefaultRatePer1KMessageColdStore], [DefaultPlanDays], [DefaultMaxMessageQuotaPerDay], [DefaultStoreHotMessage], [DefaultStoreColdMessage], [DefaultCosmosDBConnectionString], [DefaultCollectionTTL], [DefaultCollectionReservedUnits], [DefaultIoTHubConnectionString], [DefaultStorageConnectionString]) VALUES (1, N'Free Trial', N'Free Trial for 30 dyas, allow 1 msg per 10 seconds', 0, 0, 0, 30, 8640, 1, 1, N'AccountEndpoint=https://cds20-dev.documents.azure.com:443/;AccountKey=IjrxOx1UyhD5cHNK5q9GUV0lxkfQqoIvG3QWDdWWfhHHsRFVE98NOtFQIz8L29aSYY6RyDIz0sAnNUEamWg6Rw==;', 86400, 400, N'HostName=CDS20FreeTier-Dev.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=q8rdxRxeqG6ZezNIDFRndAZvruJbYt9Bj88iYdXcoOk=', N'DefaultEndpointsProtocol=https;AccountName=cds20freetrialdev;AccountKey=ePX1NwCtzSAdCK+4jhhMXKxe9bPgXjizuX8T+QyenVZZjjUcDHo8uzIBaYTZq/MHtE1MY0372UzmLhn3bpixVA==;EndpointSuffix=core.windows.net')
INSERT INTO [CDS20].[SubscriptionPlan] ([Id], [Name], [Description], [DefaultRatePer1KMessageIngestion], [DefaultRatePer1KMessageHotStore], [DefaultRatePer1KMessageColdStore], [DefaultPlanDays], [DefaultMaxMessageQuotaPerDay], [DefaultStoreHotMessage], [DefaultStoreColdMessage], [DefaultCosmosDBConnectionString], [DefaultCollectionTTL], [DefaultCollectionReservedUnits], [DefaultIoTHubConnectionString], [DefaultStorageConnectionString]) VALUES (2, N'Pro T1', N'Pro Plan with Tire 1. 400k msg/day, 10GB Hot Data, 1TB Cold Data', NULL, NULL, NULL, 365, 400000, 1, 1, N'AccountEndpoint=https://cds20-dev.documents.azure.com:443/;AccountKey=IjrxOx1UyhD5cHNK5q9GUV0lxkfQqoIvG3QWDdWWfhHHsRFVE98NOtFQIz8L29aSYY6RyDIz0sAnNUEamWg6Rw==;', 2592000, 400, NULL, NULL)
INSERT INTO [CDS20].[SubscriptionPlan] ([Id], [Name], [Description], [DefaultRatePer1KMessageIngestion], [DefaultRatePer1KMessageHotStore], [DefaultRatePer1KMessageColdStore], [DefaultPlanDays], [DefaultMaxMessageQuotaPerDay], [DefaultStoreHotMessage], [DefaultStoreColdMessage], [DefaultCosmosDBConnectionString], [DefaultCollectionTTL], [DefaultCollectionReservedUnits], [DefaultIoTHubConnectionString], [DefaultStorageConnectionString]) VALUES (3, N'Pro T2', N'Pro Plan with Tire 2. 800K msg/day, 10GB Hot Data, 2TB Cold Data', NULL, NULL, NULL, 365, 800000, 1, 1, N'AccountEndpoint=https://cds20-dev.documents.azure.com:443/;AccountKey=IjrxOx1UyhD5cHNK5q9GUV0lxkfQqoIvG3QWDdWWfhHHsRFVE98NOtFQIz8L29aSYY6RyDIz0sAnNUEamWg6Rw==;', 2592000, 400, NULL, NULL)
INSERT INTO [CDS20].[SubscriptionPlan] ([Id], [Name], [Description], [DefaultRatePer1KMessageIngestion], [DefaultRatePer1KMessageHotStore], [DefaultRatePer1KMessageColdStore], [DefaultPlanDays], [DefaultMaxMessageQuotaPerDay], [DefaultStoreHotMessage], [DefaultStoreColdMessage], [DefaultCosmosDBConnectionString], [DefaultCollectionTTL], [DefaultCollectionReservedUnits], [DefaultIoTHubConnectionString], [DefaultStorageConnectionString]) VALUES (4, N'Pro T3', N'Pro Plan with Tire 3. 2M msg/day, 10GB Hot Data, 4TB Cold Data', NULL, NULL, NULL, 365, 2000000, 1, 1, N'AccountEndpoint=https://cds20-dev.documents.azure.com:443/;AccountKey=IjrxOx1UyhD5cHNK5q9GUV0lxkfQqoIvG3QWDdWWfhHHsRFVE98NOtFQIz8L29aSYY6RyDIz0sAnNUEamWg6Rw==;', 2592000, 400, NULL, NULL)
SET IDENTITY_INSERT [CDS20].[SubscriptionPlan] OFF


INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (1, N'Azure Account', N'AzureSubscriptionId', N'f32c0770-f8db-4b27-a065-bc3c833ec96b')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (2, N'Azure Account', N'AzureResourceGroupName-Core', N'CDS20-Dev')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (3, N'Azure Account', N'AzureResourceGroupName-DataGroup', N'CDS20-DataGroup-Dev')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (11, N'Admin Web', N'AdminWebVersion', N'20170901.01')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (12, N'Admin Web', N'SuperAdminVersion', N'20170901.01')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (13, N'Admin Web', N'AdminWebURI', N'http://admin20.dev.iot-cds.net/ffff')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (14, N'Admin Web', N'GoogleMapAPIKey', N'AIzaSyBddpnG71ShFs698bfE0UvVonWVRuMqKM8')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (15, N'Admin Web', N'BaiduMapAPIKey', N'Asfer3wtwtsf354y64w3ra?wqwwerw')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (16, N'Admin Web', N'SuperAdminWebURI', N'http://superAdmin20.dev.iot-cds.net/')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (21, N'API Service', N'APIServiceBaseURI', N'http://api20.dev.iot-cds.net/')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (22, N'API Service', N'APIServiceRedisCacheEnable', N'False')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (23, N'API Service', N'ImageStorageContainer', N'images')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (24, N'API Service', N'TokenRefreshLifeTimeByHour', N'2')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (25, N'CosmosDB', N'CosmosDBConnectionString', N'AccountEndpoint=https://cds20-dev.documents.azure.com:443/;AccountKey=IjrxOx1UyhD5cHNK5q9GUV0lxkfQqoIvG3QWDdWWfhHHsRFVE98NOtFQIz8L29aSYY6RyDIz0sAnNUEamWg6Rw==;')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (26, N'CosmosDB', N'CosmosDBPartitionKey', N'/messageContent/equipmentId')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (27, N'CosmosDB', N'CollectionTTL', N'2,592,000')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (28, N'CosmosDB', N'CollectionRU', N'400')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (29, N'API Service', N'CompanyLogoWidthHeight', N'200x200')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (30, N'API Service', N'CompanyIconWidthHeight', N'50x50')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (31, N'API Service', N'FactoryPhotoWidthHeight', N'200x200')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (32, N'API Service', N'EquipmentPhotoWidthHeight', N'200x200')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (33, N'API Service', N'EmployeePhotoWidthHeight', N'200x200')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (34, N'API Service', N'EmployeeIconWidthHeight', N'50x50')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (35, N'API Service', N'ImageBgColor', N'#ffffff')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (36, N'API Service', N'ImageConvertFormat', N'JPG')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (41, N'Log', N'ProvisionLogStorageContainerApp', N'log-backend-provision')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (42, N'Log', N'ProvisionLogLevel', N'Info')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (43, N'Log', N'IoTHubReceiverLogStorageContainerApp', N'log-backend-iothubreceiver')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (44, N'Log', N'IoTHubReceiverLogLevel', N'Info')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (45, N'Log', N'EventActionLogStorageContainerApp', N'log-backend-eventaction')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (46, N'Log', N'EventActionLogLevel', N'Info')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (47, N'Log', N'APIServiceLogStorageContainerApp', N'log-apiservice')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (48, N'Log', N'APIServiceLogLevel', N'Info')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (49, N'Log', N'DeviceLogStorageContainer', N'log-device')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (50, N'Log', N'MsgHubServiceLogStorageContainerApp', N'log-msghub')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (51, N'Log', N'MsgHubServiceLogLevel', N'Info')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (52, N'Log', N'ScheduleLogStorageContainerApp', N'log-backend-schedule')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (53, N'Log', N'ScheduleLogLevel', N'Info')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (54, N'Log', N'EmailAppLogStorageContainerApp', N'log-backend-email')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (55, N'Log', N'EmailAppLogLevel', N'Info')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (56, N'Log', N'SMSAppLogStorageContainerApp', N'log-backend-sms')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (57, N'Log', N'SMSAppLogLevel', N'Info')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (61, N'MessageHub', N'AdminHeartbeatURL', N'http://msghub20.dev.iot-cds.net/AdminHeartbeat/FeedIn')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (62, N'MessageHub', N'SuperAdminHeartbeatURL', N'http://msghub20.dev.iot-cds.net/SuperAdminHeartbeat/FeedIn')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (63, N'MessageHub', N'RTMessageFeedInURL', N'http://msghub20.dev.iot-cds.net/Message/FeedIn')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (64, N'MessageHub', N'RTEventFeedInURL', N'http://msghub20.dev.iot-cds.net/Event/FeedIn')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (65, N'MessageHub', N'MessageHubAllowIPStart', N'0.0.0.0')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (66, N'MessageHub', N'MessageHubAllowIpEnd', N'255.255.255.255')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (67, N'MessageHub', N'MessageHubURI', N'http://msghub20.dev.iot-cds.net/')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (71, N'Redis Cache', N'RedisCacheConnectionString', N'cds20-dev.redis.cache.windows.net:6380,password=4CZD/DLmJVm3lc9pcBoEnCcBzJ82ls18TNn7/gs0gVs=,ssl=True,abortConnect=False')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (72, N'Redis Cache', N'DefaultRedisCacheTTL', N'86400')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (73, N'Redis Cache', N'PrefixSystemLevelCacheKey', N'system')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (74, N'Redis Cache', N'PrefixCompanyLevelCacheKey', N'C_{companyId}')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (75, N'Redis Cache', N'KeyOfMessageQuotaPerDay', N'C_{companyId}_MessageQuotaPerDay')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (81, N'Service Bus', N'ServiceBusConnectionString', N'Endpoint=sb://cds20servicebus-dev.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=8x6gjqalTGuXbbqnXD2ltqu0UBSlohoz0WivqmnOPaU=')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (82, N'Service Bus', N'ProvisionQueue', N'provision')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (83, N'Service Bus', N'EventActionQueue', N'event-action')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (84, N'Service Bus', N'IoTHubReceiverTopic', N'iothubreceiver')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (85, N'Storage Account', N'SystemStorageName', N'cds20systemstoragedev')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (86, N'Storage Account', N'SystemStorageKey', N'64SCgh/hP9PjCCY6YljAcf4E/kCCh58pUoscfzxnUYfNSwRw8ZYLgN+5wVgWUC5njqax6A1c1BK/GT45hNEwWQ==')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (87, N'Storage Account', N'TelemetryStorageContainer', N'telemetry')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (88, N'Storage Account', N'EventStorageContainer', N'event')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (91, N'Service Fabric', N'ServiceFabricURI', N'https://cds20.southeastasia.cloudapp.azure.com:19080/')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (92, N'Service Fabric', N'SrvFabricIoTHubReceiverTypeName', N'IoTHubReceiverStaging')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (93, N'Service Fabric', N'SrvFabricIoTHubReceiverTypeVersion', N'2.1.3')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (94, N'Service Fabric', N'SrvFabricCertificateLocation', N'srvfabric/srvFabricSelfSigned.pfx')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (95, N'Service Fabric', N'SrvFabricCertificatePassword', N'``1qaz2wsx')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (101, N'Microservice', N'ProvisionAppHeartbeatIntervalinSec', N'10')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (102, N'Microservice', N'EventActionAppHeartbeatIntervalinSec', N'10')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (131, N'Microservice', N'EmailAppHeartbeatIntervalinSec', N'10')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (132, N'Microservice', N'EmailSendGridKey', N'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')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (133, N'Microservice', N'SMSTwilioAccountId', N'AC0a222b8ee3da33ff9f90f89b629a1ef6')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (134, N'Microservice', N'SMSTwillioToken', N'fa46a700c072980cd35f8922f0ed1af2')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (135, N'Microservice', N'SMSTwilloPhoneNumber', N'+12067354674')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (136, N'Microservice', N'SMSAppHeartbeatIntervalInSec', N'10')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (137, N'Microservice', N'HTTPAppHeartbeatIntervalInSec', N'10')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (138, N'Microservice', N'IoTHubReceiverHeartbeatIntervalInSec', N'10')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (181, N'Service Bus', N'EmailQueue', N'email')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (182, N'Service Bus', N'SMSQueue', N'sms')
INSERT INTO [CDS20].[SystemConfiguration] ([Id], [Group], [Key], [Value]) VALUES (183, N'Service Bus', N'HTTPQueue', N'http')





INSERT INTO [CDS20].[APIServiceRole] ([Name]) VALUES (N'admin')
INSERT INTO [CDS20].[APIServiceRole] ([Name]) VALUES (N'device')
INSERT INTO [CDS20].[APIServiceRole] ([Name]) VALUES (N'external')
INSERT INTO [CDS20].[APIServiceRole] ([Name]) VALUES (N'superadmin')

